<?php

/**
 * @var Overdose\LessonCrud\ViewModel\Two $viewModel
 * @var Magento\Framework\View\Element\Template $block
 */

$viewModel = $block->getData('view_model'); // view_model - нейм аргументу в xml

echo $viewModel->iAmViewModel(); //var2

//Call new function with write db
try {
    echo $viewModel->saveNewFriend('Ivan', '60', 'Cool guy');
} catch (\Magento\Framework\Exception\AlreadyExistsException $e) {
}

// Return collection product
//var_dump($viewModel->getProductCollection());

// Повернути всіх друзів з таблиці
echo "<br>";
var_dump($viewModel->gelAllFriends());
echo "<br>";

$productCollection = $viewModel->getProductCollection();
foreach ($productCollection as $product) {
    print_r($product->getData()['name']);
    //echo "<br>";
}

?>

<p>Hello words</p>
